# Lexik maintenance configuration
lexik_maintenance:
    authorized:
        path: /maintenance   # Optional. Authorized path, accepts regexs
        host: "%web_path%"    # Optional. Authorized domain, accepts regexs
        ips: ['127.0.0.1']   # Optional. Authorized ip addresses                                                     # Optional. Authorized route attributes
    driver:
        ttl: 3600            # Optional ttl option, can be not set
         # File driver
        class: '\Lexik\Bundle\MaintenanceBundle\Drivers\FileDriver'    # class for file driver