fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

project_bundle:
    resource: "@ProjectBundle/Resources/config/routing.yml"
    prefix: /

eurosites_bundle:
    resource: "@EurositesBundle/Resources/config/routing.yml"
    prefix: /eurosites